"""
GUI共通定数
"""
# ダイアログやリスト等のサイズ定数
DIALOG_SIZE = (400, 350)
DETAIL_AREA_MIN_WIDTH = 600
DETAIL_AREA_MAX_WIDTH = 2000
SCREEN_LIST_MIN_WIDTH = 180
SCREEN_LIST_MAX_WIDTH = 250
SCREEN_LIST_FIXED_WIDTH = 220
SCROLL_LEFT_FIXED_WIDTH = 230
LIST_WIDGET_MIN_WIDTH = 350
LIST_WIDGET_MAX_WIDTH = 350
LIST_WIDGET_MIN_HEIGHT = 200

# CSVサンプル（画面名,シナリオ名,ステータス,最終実行日,実行結果）
CSV_SAMPLE = (
    "画面A,シナリオ1,未実行,-,-\n"
    "画面A,シナリオ2,未実行,-,-\n"
    "画面B,シナリオX,合格,2025/06/01,合格\n"
)
